import { expect, test } from "@playwright/test";
import { login, nextClientIp } from "./fixtures";

test("bulk import readings, link primary, and remove equipment for reimport", async ({ page }, testInfo) => {
  page.setDefaultTimeout(10_000);
  await page.context().setExtraHTTPHeaders({ "x-forwarded-for": nextClientIp() });
  const viewport = testInfo.project.name;
  const name = `E2E ${viewport} motion`;
  const temperature = `sensor.e2e_${viewport}_temperature`;
  const battery = `sensor.e2e_${viewport}_battery`;
  const disabledSignal = `sensor.e2e_${viewport}_signal`;
  const occupancy = `binary_sensor.e2e_${viewport}_occupancy`;
  await login(page, "lucas", { next: "/settings/home-assistant" });
  await page.getByRole("checkbox", { name: `Select ${name} for bulk import`, exact: true }).check();
  await expect(page.getByRole("combobox", { name: `Role for ${battery}`, exact: true })).toBeVisible();
  await expect(page.getByRole("combobox", { name: `Role for ${disabledSignal}`, exact: true })).toHaveCount(0);
  const humidityRole = page.getByRole("combobox", { name: `Role for sensor.e2e_${viewport}_humidity`, exact: true });
  await expect(humidityRole.locator("xpath=ancestor::li[1]").getByText("Unavailable", { exact: true })).toBeVisible();
  await page.getByRole("switch", { name: "Show disabled and hidden things", exact: true }).click();
  const disabledRole = page.getByRole("combobox", { name: `Role for ${disabledSignal}`, exact: true });
  await expect(disabledRole.locator("xpath=ancestor::li[1]").getByText("Disabled", { exact: true })).toBeVisible();
  await page.getByRole("switch", { name: "Show disabled and hidden things", exact: true }).click();
  await expect(disabledRole).toHaveCount(0);
  await page.getByRole("combobox", { name: `Role for ${temperature}`, exact: true }).click();
  const popup = page.locator("[data-vh-select-popup]");
  const popupBox = (await popup.boundingBox())!;
  expect(popupBox.width).toBeGreaterThanOrEqual(320);
  expect(popupBox.x).toBeGreaterThanOrEqual(0);
  expect(popupBox.x + popupBox.width).toBeLessThanOrEqual((await page.evaluate(() => innerWidth)) + 1);
  await page.getByRole("option", { name: /^Status \/ reading/ }).click();
  await page.getByRole("button", { name: "Import 1", exact: true }).click();
  await expect(page.getByText(`Already ${name}`, { exact: true })).toBeVisible();
  await page.getByRole("switch", { name: "Hide already imported", exact: true }).check();
  await expect(page.getByText(`Already ${name}`, { exact: true })).toHaveCount(0);
  await page.getByRole("switch", { name: "Hide already imported", exact: true }).uncheck();
  await expect(page.getByText(`Already ${name}`, { exact: true })).toBeVisible();
  await testInfo.attach("ha-import-aligned-rows.png", { body: await page.screenshot(), contentType: "image/png" });
  await page.goto("/equipment");
  await expect(page.getByRole("link", { name: "Import from Home Assistant", exact: true })).toBeVisible();
  await page.getByRole("link", { name: new RegExp(name) }).click();
  await expect(page).toHaveURL(/\/equipment\/[^/?]+$/);
  await expect(page.getByText(temperature, { exact: true })).toBeVisible();
  const equipmentUrl = page.url();
  await page.getByRole("button", { name: "Link an entity", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("combobox", { name: /^Entity/ }).click();
  const optionSearch = page.getByRole("searchbox", { name: "Search options", exact: true });
  await expect(optionSearch).toBeFocused();
  await optionSearch.fill("battery");
  await expect(page.getByRole("option").filter({ hasText: battery })).toBeVisible();
  await optionSearch.press("Escape");
  await expect(optionSearch).toBeHidden();
  await expect(dialog).toBeVisible();
  await dialog.getByRole("combobox", { name: /^Entity/ }).click();
  await expect(page.getByRole("option").first()).toContainText(`e2e_${viewport}_`);
  await expect(page.getByRole("option").filter({ hasText: battery })).toHaveCount(1);
  await expect(page.getByRole("option").filter({ hasText: disabledSignal })).toHaveCount(0);
  await page.getByRole("option").filter({ hasText: occupancy }).click();
  await dialog.getByRole("button", { name: "Link it", exact: true }).click();
  await expect(dialog).toBeHidden();
  await page.reload();
  await expect(page.getByText(occupancy, { exact: true })).toBeVisible();
  await expect(page.getByText("Primary", { exact: true })).toBeVisible();

  await page.goto("/equipment");
  const sections = page.getByRole("navigation", { name: "Sections", exact: true }).filter({ visible: true });
  for (const label of ["Equipment", "Projects", "Plans", "Procedures", "Shopping list"]) {
    await expect(sections.getByRole("link", { name: label, exact: true })).toBeAttached();
  }
  await page.getByRole("searchbox", { name: "Filter equipment" }).fill(name);
  await page.getByRole("checkbox", { name: "Select all filtered", exact: true }).check();
  await page.getByRole("button", { name: "Remove selected", exact: true }).click();
  await expect(dialog).toContainText(name);
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("link", { name: new RegExp(name) })).toBeVisible();
  await page.getByRole("button", { name: "Remove selected", exact: true }).click();
  await dialog.getByRole("button", { name: "Remove 1", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole("link", { name: new RegExp(name) })).toHaveCount(0);
  await page.getByRole("link", { name: "Import from Home Assistant", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: `Select ${name} for bulk import`, exact: true })).toBeVisible();
  await expect(page.getByText(`Already ${name}`, { exact: true })).toHaveCount(0);
  // Archived equipment is preserved in history but must not reappear in the viewer's placeable list.
  const placeableResponse = await page.request.get("/api/house-model/fixture-house/placements?options=placeable");
  expect(placeableResponse.ok()).toBe(true);
  const { placeable } = await placeableResponse.json() as { placeable: { name: string }[] };
  expect(placeable.filter((row) => row.name === name)).toHaveLength(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);

  await page.goto("/equipment");
  await page.getByRole("link", { name: "Systems", exact: true }).click();
  await expect(page).toHaveURL(/\/equipment\/systems$/);
  await expect(page.getByRole("heading", { name: "Systems", exact: true, level: 1 })).toBeVisible();
  await page.getByRole("button", { name: "New system", exact: true }).click();
  await expect(dialog.getByRole("textbox", { name: /^Name/ })).toHaveValue("");
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("link", { name: "All equipment", exact: true }).click();
  await page.getByRole("link", { name: "Trash", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Equipment trash", exact: true })).toBeVisible();
  await page.getByRole("searchbox", { name: "Filter equipment" }).fill(name);
  await page.getByRole("checkbox", { name: "Select all filtered", exact: true }).check();
  if (viewport === "desktop") await page.setViewportSize({ width: 1000, height: 850 });
  const selectionSummary = page.getByText(/shown · .* selected · up to/);
  const deleteButton = page.getByRole("button", { name: "Delete permanently", exact: true });
  const summaryBox = await selectionSummary.boundingBox();
  const buttonBox = await deleteButton.boundingBox();
  expect(summaryBox).not.toBeNull();
  expect(buttonBox).not.toBeNull();
  expect(summaryBox!.y + summaryBox!.height <= buttonBox!.y || summaryBox!.x + summaryBox!.width <= buttonBox!.x).toBe(true);
  await testInfo.attach("equipment-trash-toolbar.png", { body: await page.screenshot(), contentType: "image/png" });
  await deleteButton.click();
  await expect(dialog).toContainText(name);
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("link", { name: new RegExp(name) })).toBeVisible();
  await deleteButton.click();
  await dialog.getByRole("button", { name: "Delete permanently", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole("link", { name: new RegExp(name) })).toHaveCount(0);
  // Next can stream a not-found page with HTTP 200 once its shell was sent.
  await page.goto(equipmentUrl);
  await expect(page.getByRole("heading", { name: "404", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
