"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button, Dialog, Input } from "@/ui";
import { createMember, removeMemberPasskeys, resetMemberPassword, saveMember } from "@/server/actions/settings/members";
import { useAction } from "@/features/settings/actionClient";
import type { HouseholdMember } from "@/server/queries/settings/users";
const messages = { user_exists: "That username is already in use.", invalid_username: "Use 3–30 lowercase letters, digits, dots, underscores or hyphens.", owner_required: "Only an owner can manage members.", last_owner: "Keep at least one active owner.", replacement_required: "Choose an active member to receive open work.", last_member: "Keep at least one active member." };
const field = "min-h-11 w-full rounded border border-line bg-surface px-3";
export function CreateMember() {
  const [open, setOpen] = useState(false); const router = useRouter();
  const create = useAction(createMember, { messages, successTitle: "Member created", onSuccess: () => { setOpen(false); router.refresh(); } });
  return <Dialog open={open} onOpenChange={setOpen} title="Add household member" description="Members can use household features. Owners also manage accounts." trigger={<Button>Add member</Button>}><form data-unsaved className="space-y-3" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); create.run({ username: String(data.get("username")), name: String(data.get("name")), password: String(data.get("password")) }); }}><label className="block">Name<Input name="name" required maxLength={120}/></label><label className="block">Username<Input name="username" required minLength={3} maxLength={30} pattern="[a-z0-9][a-z0-9._-]{2,29}" autoComplete="off"/></label><label className="block">Initial password<Input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><p className="text-sm text-ink-3">Share the password privately. They can change it in Security.</p>{create.error && <p role="alert">{create.error}</p>}<Button type="submit" loading={create.pending}>Create member</Button></form></Dialog>;
}
export function ManageMember({ member, members }: { member: HouseholdMember; members: HouseholdMember[] }) {
  const [open, setOpen] = useState(false), [active, setActive] = useState(member.active); const router = useRouter();
  const save = useAction(saveMember, { messages, successTitle: "Member saved", onSuccess: () => { setOpen(false); router.refresh(); } });
  const reset = useAction(resetMemberPassword, { messages, successTitle: "Password reset; sessions revoked", onSuccess: () => { setOpen(false); router.refresh(); } });
  return <Dialog open={open} onOpenChange={next => { setOpen(next); if (next) setActive(member.active); }} title={`Manage ${member.name}`} description="History keeps this person's name. Deactivation stops access and moves open work." trigger={<Button variant="secondary" size="sm">Manage member</Button>}><form data-unsaved className="space-y-3" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); save.run({ userId: member.id, username: String(data.get("username")), name: String(data.get("name")), role: String(data.get("role")) as "owner" | "member", active, replacementId: active ? undefined : data.get("replacementId") === "shared" ? null : String(data.get("replacementId")) }); }}><label className="block">Name<Input name="name" defaultValue={member.name} required maxLength={120}/></label><label className="block">Username<Input name="username" defaultValue={member.username ?? ""} required minLength={3} maxLength={30} pattern="[a-z0-9][a-z0-9._-]{2,29}" autoComplete="off"/></label><label className="block">Access<select name="role" aria-label="Access" defaultValue={member.role} className={field}><option value="member">Member</option><option value="owner">Owner — manages accounts</option></select></label><label className="flex gap-2"><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)}/>Active account</label>{!active && <label className="block">Move open work to<select name="replacementId" aria-label="Move open work to" required className={field}><option value="">Choose who receives the work</option><option value="shared">Shared household work</option>{members.filter(row => row.active && row.id !== member.id).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>}{!active && <p className="text-sm text-ink-3">Sign-ins, AI connections and reminders stop. Restoring access does not restore old connections or assignments.</p>}{save.error && <p role="alert">{save.error}</p>}<Button type="submit" loading={save.pending}>Save member</Button></form><form data-unsaved className="mt-5 space-y-3 border-t border-line pt-4" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); reset.run({ userId: member.id, password: String(data.get("password")) }); }}><label className="block">New password<Input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label>{reset.error && <p role="alert">{reset.error}</p>}<Button type="submit" variant="secondary" loading={reset.pending}>Reset password and sign out sessions</Button><p className="text-sm text-ink-3">A reset keeps {member.name}&apos;s passkeys. Remove them below if a device was lost.</p></form><RemovePasskeys member={member} onDone={() => { setOpen(false); router.refresh(); }}/></Dialog>;
}
/**
 * The owner's explicit passkey removal. Two steps because nothing undoes it: the member has to
 * register the passkeys again from their own devices. Sessions stay — the password reset above is
 * what signs devices out.
 */
function RemovePasskeys({ member, onDone }: { member: HouseholdMember; onDone: () => void }) {
  const [confirming, setConfirming] = useState(false);
  const remove = useAction(removeMemberPasskeys, { messages, successTitle: "Passkeys removed", successDescription: data => `${data.removed} passkey${data.removed === 1 ? "" : "s"} deleted. Signed-in devices stay signed in.`, onSuccess: () => { setConfirming(false); onDone(); } });
  const count = member.passkeyCount;
  return <section aria-label={`Passkeys for ${member.name}`} className="mt-5 space-y-3 border-t border-line pt-4"><p className="text-sm">{count === 0 ? `${member.name} has no passkeys.` : `${member.name} has ${count} passkey${count === 1 ? "" : "s"}.`}</p>{count > 0 && !confirming && <Button type="button" variant="secondary" onClick={() => setConfirming(true)}>Remove passkeys</Button>}{count > 0 && confirming && <div className="space-y-2"><p className="text-sm text-ink-2">Delete all {count} passkey{count === 1 ? "" : "s"}? {member.name} signs in with the password until they add new ones.</p><div className="flex gap-2"><Button type="button" variant="danger" loading={remove.pending} onClick={() => remove.run({ userId: member.id })}>Remove all passkeys</Button><Button type="button" variant="ghost" disabled={remove.pending} onClick={() => setConfirming(false)}>Cancel</Button></div></div>}{remove.error && <p role="alert">{remove.error}</p>}</section>;
}
