import { z } from "zod";
import { getDb } from "@/db/client";
import { haControlCommandSchema } from "@/domain/haControl";
import { authed, notFound } from "@/server/api/handler";
import { readEquipmentHaControls } from "@/server/ha/control";
import { runOperation } from "@/server/operations/core";
import { queueHaControl } from "@/server/operations/ha/control";
type Ctx={params:Promise<{assetId:string}>};
export const dynamic="force-dynamic";
const inputSchema=z.object({requestId:z.uuid(),registryId:z.string().min(1).max(255),command:haControlCommandSchema}).strict();
const noStore={"Cache-Control":"private, no-store",Vary:"Cookie"} as const;
export const GET=authed<Ctx>(async(_session,_req,ctx)=>{const {assetId}=await ctx.params;const controls=readEquipmentHaControls(getDb().db,assetId);if(!controls)throw notFound("equipment_not_found");return Response.json(controls,{headers:noStore});});
export const POST=authed<Ctx>(async(session,req,ctx)=>{const {assetId}=await ctx.params;const input=inputSchema.parse(await req.json());const {data}=runOperation(queueHaControl,{...input,assetId},session);return Response.json(data,{status:202,headers:noStore});});
